### ISSUE TITLE
Calling zoneinfo on a file without transition times panics

### ISSUE THREAD

**Issue by MaeIsBad** [nicolasbauw/rs-tzfile#3]
The panic occurs due to a 'index out of bounds: the len is 0 but the index is 0', error in 
https://github.com/nicolasbauw/rs-tzfile/blob/master/src/lib.rs#L389

Steps to reproduce:
use the library on a zoneinfo file without transition times, for example `/usr/share/zoneinfo/EST`

**Comment by nicolasbauw** [comment]
Thanks for pointing this out.
In such a case the function now returns a NoData error.

I still have to rework the zoneinfo function, because if the timezone has no transition times, it also returns a (non-panicking) error, instead of a proper Tzinfo struct.

**Comment by nicolasbauw** [comment]
[Fixed] Issue #3 (Calling zoneinfo on a file without transition times panics)
[Added] Proper handling of TZFiles without transition times by the zoneinfo() function
