### ISSUE TITLE
Possible to relicense as Apache-2/MIT?

### ISSUE THREAD

**Issue by Manishearth** [nicolasbauw/rs-tzfile#4]
Hi!

Most Rust crates are dual-licensed under MIT and Apache-2. We're interested in using this in [ICU4X](https://github.com/unicode-org/icu4x) and were wondering if this crate could be relicensed to match so that it's license compatible with more of the Rust ecosystem.

Totally understandable if your answer is no, I get that lots of people pick GPL on purpose and that's fine too.

**Comment by nicolasbauw** [comment]
Hi,
MIT license is OK for me.

**Comment by nicolasbauw** [comment]
License changed to MIT in 2.0.3

**Comment by Manishearth** [comment]
Thank you!
